### ISSUE TITLE
Be consistent with how you're adding elements

### ISSUE THREAD

**Issue by mantagen** [FACN1/week2-javiasy#70]
https://github.com/FACN1/week2-javiasy/blob/master/todo.js#L116
https://github.com/FACN1/week2-javiasy/blob/master/todo.js#L142

Is there a reason you're mixing up `.innerHTML=` and `.createElement()`?

**Comment by macintoshhelper** [comment]
Pull request created to fix this issue: https://github.com/FACN1/week2-javiasy/pull/81
