### ISSUE TITLE
why this?

### ISSUE THREAD

**Issue by mattlub** [FACN1/week2-javiasy#75]
Why use 'this' here? Just curious.

https://github.com/FACN1/week2-javiasy/blob/master/todo.js#L27

**Comment by jwld** [comment]
It's a way to reference a function on the same parent object. I guess the alternative would be todoFunctions.generateId()?

**Comment by macintoshhelper** [comment]
~~Using "this" is likely better, since if the parent name is changed, addTodo will continue to work.~~

Ignore above: look at issue #72 .

**Comment by mattlub** [comment]
cool- I agree, and also it reads more clearly.
